"""wave04 canonical relational schema

Revision ID: eebb1d156a98
Revises:
Create Date: 2026-08-10 20:10:11.682711
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eebb1d156a98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_versions',
    sa.Column('config_kind', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_versions')),
    sa.UniqueConstraint('config_kind', 'version', name='uq_config_kind_version'),
    sa.UniqueConstraint('content_sha256', name='uq_config_content_hash')
    )
    op.create_table('organizations',
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('organization_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('canonical_key', name='uq_organization_canonical_key')
    )
    op.create_index('ix_organization_normalized_name', 'organizations', ['normalized_name'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('run_type', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='pipeline_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=160), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_pipeline_runs_correlation_id'))
    )
    op.create_index('ix_pipeline_run_status_time', 'pipeline_runs', ['status', 'started_at'], unique=False)
    op.create_table('project_groups',
    sa.Column('canonical_name', sa.String(length=320), nullable=False),
    sa.Column('normalized_name', sa.String(length=320), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('group_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_groups')),
    sa.UniqueConstraint('canonical_key', name='uq_project_group_canonical_key')
    )
    op.create_index(op.f('ix_project_groups_normalized_name'), 'project_groups', ['normalized_name'], unique=False)
    op.create_table('source_documents',
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('report_type', sa.String(length=120), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_ref', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=80), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('source_type', 'content_sha256', name='uq_source_document_type_hash')
    )
    op.create_index('ix_source_documents_external', 'source_documents', ['source_system', 'external_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('safe_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_audit_events_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_event_actor_time', 'audit_events', ['actor_type', 'actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_event_object_time', 'audit_events', ['object_type', 'object_id', 'occurred_at'], unique=False)
    op.create_table('field_history',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=160), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=60), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commercial_impact', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_field_history_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_field_history_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_history'))
    )
    op.create_index('ix_field_history_entity_field', 'field_history', ['entity_type', 'entity_id', 'field_name'], unique=False)
    op.create_table('persons',
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('current_organization_id', sa.Uuid(), nullable=True),
    sa.Column('employment_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='person_employment_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_organization_id'], ['organizations.id'], name=op.f('fk_persons_current_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index('ix_person_normalized_name', 'persons', ['normalized_name'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('safe_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_pipeline_events_pipeline_run_id_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_events')),
    sa.UniqueConstraint('pipeline_run_id', 'sequence_number', name='uq_pipeline_event_sequence')
    )
    op.create_index('ix_pipeline_event_run_time', 'pipeline_events', ['pipeline_run_id', 'occurred_at'], unique=False)
    op.create_table('projects',
    sa.Column('project_group_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_name', sa.String(length=400), nullable=False),
    sa.Column('normalized_name', sa.String(length=400), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('state', sa.Enum('INGESTED', 'PARSED', 'VALIDATED', 'QUALIFIED', 'ACCOUNT_RESOLVED', 'CONTACT_RESOLUTION', 'CRM_READY', 'ACTIVE_LEAD', 'DEMO', 'WON', 'LOST', name='project_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('stage', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('reported_value', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_group_id'], ['project_groups.id'], name=op.f('fk_projects_project_group_id_project_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('canonical_key', name='uq_project_canonical_key'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_project_source_external_id')
    )
    op.create_index('ix_project_stage', 'projects', ['state', 'stage'], unique=False)
    op.create_index(op.f('ix_projects_normalized_name'), 'projects', ['normalized_name'], unique=False)
    op.create_table('prompt_runs',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('task', sa.String(length=160), nullable=False),
    sa.Column('prompt_name', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('response_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='prompt_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_prompt_runs_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_runs'))
    )
    op.create_index('ix_prompt_run_task_time', 'prompt_runs', ['task', 'started_at'], unique=False)
    op.create_table('scoring_configs',
    sa.Column('config_version_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('pursue_threshold', sa.Float(), nullable=True),
    sa.Column('review_threshold', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['config_versions.id'], name=op.f('fk_scoring_configs_config_version_id_config_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_configs')),
    sa.UniqueConstraint('config_version_id', 'model_name', name='uq_scoring_config_version_model')
    )
    op.create_table('ai_usage',
    sa.Column('prompt_run_id', sa.Uuid(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], name=op.f('fk_ai_usage_prompt_run_id_prompt_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage')),
    sa.UniqueConstraint('prompt_run_id', name='uq_ai_usage_prompt_run')
    )
    op.create_table('commercial_motions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('motion_type', sa.Enum('CONTRACTOR', 'RENTAL_HOUSE', name='motion_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('UNRESOLVED', 'DISCOVERY', 'VALIDATING', 'READY', 'ACTIVE', 'CLOSED', name='motion_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('demand_strength', sa.String(length=40), nullable=True),
    sa.Column('confidence_state', sa.Enum('UNKNOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CONFLICTED', name='motion_confidence_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commercial_motions_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_commercial_motions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commercial_motions')),
    sa.UniqueConstraint('project_id', 'motion_type', name='uq_commercial_motion_project_type')
    )
    op.create_table('contact_candidates',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('DISCOVERED', 'EMPLOYMENT_VERIFIED', 'PROJECT_ASSOCIATION_VERIFIED', 'ROLE_RELEVANT', 'AUTHORITY_VERIFIED', name='contact_candidate_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('candidate_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('target_persona', sa.String(length=160), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('candidate_score IS NULL OR (candidate_score >= 0 AND candidate_score <= 100)', name=op.f('ck_contact_candidates_candidate_score_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contact_candidates_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_contact_candidates_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contact_candidates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_candidates')),
    sa.UniqueConstraint('project_id', 'person_id', name='uq_contact_candidate_project_person')
    )
    op.create_index('ix_contact_candidate_project_rank', 'contact_candidates', ['project_id', 'rank'], unique=False)
    op.create_table('crm_records',
    sa.Column('crm_system', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.Enum('ORGANIZATION', 'PERSON', 'LEAD', 'DEAL', name='crm_object_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('promotion_state', sa.Enum('INTELLIGENCE', 'LEAD', 'DEAL', name='crm_promotion_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'PREVIEWED', 'SUCCEEDED', 'FAILED', 'BLOCKED', name='crm_record_sync_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crm_records_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_crm_records_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_crm_records_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_records')),
    sa.UniqueConstraint('crm_system', 'object_type', 'canonical_key', name='uq_crm_canonical_object'),
    sa.UniqueConstraint('crm_system', 'object_type', 'external_id', name='uq_crm_external_object')
    )
    op.create_table('external_evidence',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=600), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='external_evidence_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('verification_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='external_evidence_verification_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_state', sa.Enum('UNKNOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CONFLICTED', name='external_evidence_confidence_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pii_class', sa.Enum('NONE', 'PUBLIC_BUSINESS', 'BUSINESS_CONTACT', 'PERSONAL_CONTACT', 'SENSITIVE', 'SECRET', name='external_evidence_pii_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('demo_masking_policy', sa.Enum('NONE', 'PARTIAL', 'FULL', 'HIDDEN', name='external_evidence_masking_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_external_evidence_confidence_score_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_external_evidence_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_external_evidence_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_external_evidence_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_evidence')),
    sa.UniqueConstraint('evidence_fingerprint', name='uq_external_evidence_fingerprint')
    )
    op.create_index('ix_external_evidence_subject', 'external_evidence', ['project_id', 'organization_id', 'person_id'], unique=False)
    op.create_table('opportunity_assessments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scoring_config_id', sa.Uuid(), nullable=True),
    sa.Column('commercial_fit_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('data_confidence_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('confidence_state', sa.Enum('UNKNOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CONFLICTED', name='opportunity_confidence_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('commercial_fit_score >= 0 AND commercial_fit_score <= 100', name=op.f('ck_opportunity_assessments_fit_score_range')),
    sa.CheckConstraint('data_confidence_score >= 0 AND data_confidence_score <= 100', name=op.f('ck_opportunity_assessments_confidence_score_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_opportunity_assessments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_config_id'], ['scoring_configs.id'], name=op.f('fk_opportunity_assessments_scoring_config_id_scoring_configs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_assessments'))
    )
    op.create_index('ix_opportunity_assessment_project_current', 'opportunity_assessments', ['project_id', 'computed_at'], unique=False)
    op.create_table('source_observations',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('field_name', sa.String(length=160), nullable=False),
    sa.Column('value_type', sa.Enum('TEXT', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'MONEY', 'ENUM', 'IDENTIFIER', name='value_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('normalized_integer', sa.BigInteger(), nullable=True),
    sa.Column('normalized_decimal', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalized_boolean', sa.Boolean(), nullable=True),
    sa.Column('normalized_date', sa.Date(), nullable=True),
    sa.Column('normalized_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('observation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evidence_classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='evidence_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_state', sa.Enum('UNKNOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CONFLICTED', name='confidence_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('validation_state', sa.Enum('UNVALIDATED', 'VALID', 'INVALID', 'CONFLICTED', 'REQUIRES_REVIEW', 'QUARANTINED', name='validation_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scoring_treatment', sa.Enum('FULL', 'CAPPED', 'EXCLUDED', 'REVIEW', name='scoring_treatment', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_source_observations_confidence_score_range')),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_source_observations_document_id_source_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_source_observations_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_source_observations_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_source_observations_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_observations')),
    sa.UniqueConstraint('observation_fingerprint', name='uq_source_observation_fingerprint')
    )
    op.create_index('ix_source_observation_field', 'source_observations', ['field_name'], unique=False)
    op.create_index('ix_source_observation_org', 'source_observations', ['organization_id'], unique=False)
    op.create_index('ix_source_observation_person', 'source_observations', ['person_id'], unique=False)
    op.create_index('ix_source_observation_project', 'source_observations', ['project_id'], unique=False)
    op.create_table('ai_claims',
    sa.Column('prompt_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('claim_type', sa.String(length=120), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='ai_claim_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('validation_state', sa.Enum('UNVALIDATED', 'VALID', 'INVALID', 'CONFLICTED', 'REQUIRES_REVIEW', 'QUARANTINED', name='ai_claim_validation_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'GROUNDED', 'REJECTED', 'ACCEPTED', name='ai_claim_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('accepted_observation_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_observation_id'], ['source_observations.id'], name=op.f('fk_ai_claims_accepted_observation_id_source_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_claims_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_ai_claims_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_claims_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], name=op.f('fk_ai_claims_prompt_run_id_prompt_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_claims'))
    )
    op.create_index('ix_ai_claim_run_status', 'ai_claims', ['prompt_run_id', 'status'], unique=False)
    op.create_table('assessment_factors',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('factor_key', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('raw_points', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('adjusted_points', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cap_points', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='assessment_factor_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['opportunity_assessments.id'], name=op.f('fk_assessment_factors_assessment_id_opportunity_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_assessment_factors_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_factors')),
    sa.UniqueConstraint('assessment_id', 'factor_key', name='uq_assessment_factor_key')
    )
    op.create_table('commercial_outcomes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('contact_candidate_id', sa.Uuid(), nullable=True),
    sa.Column('commercial_motion_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_type', sa.Enum('NO_RESPONSE', 'RESPONDED', 'INTERESTED', 'DEMO_BOOKED', 'DEMO_COMPLETED', 'RENTAL_PARTNER_IDENTIFIED', 'WON', 'LOST', 'GOOD_FIT', 'POOR_FIT', 'NO_NEED', 'NOT_NOW', 'RIGHT_PERSON', 'WRONG_PERSON', 'LEFT_COMPANY', name='commercial_outcome_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('loss_reason', sa.Enum('INCUMBENT_SUPPLIER', 'TIMING', 'PRICE', 'PRODUCT_FIT', 'BUDGET', 'AUTHORITY', 'OTHER', name='loss_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commercial_motion_id'], ['commercial_motions.id'], name=op.f('fk_commercial_outcomes_commercial_motion_id_commercial_motions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_candidate_id'], ['contact_candidates.id'], name=op.f('fk_commercial_outcomes_contact_candidate_id_contact_candidates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_commercial_outcomes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commercial_outcomes'))
    )
    op.create_index('ix_commercial_outcome_project_time', 'commercial_outcomes', ['project_id', 'observed_at'], unique=False)
    op.create_table('contact_assessments',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('employment_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='contact_employment_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('project_association_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='contact_project_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role_relevance_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='contact_role_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rental_authority_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='contact_authority_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['contact_candidates.id'], name=op.f('fk_contact_assessments_candidate_id_contact_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_assessments'))
    )
    op.create_index('ix_contact_assessment_candidate_time', 'contact_assessments', ['candidate_id', 'assessed_at'], unique=False)
    op.create_table('crm_sync_attempts',
    sa.Column('crm_record_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('OFF', 'PREVIEW', 'DRY_RUN', 'LIVE', name='crm_sync_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREVIEWED', 'SUCCEEDED', 'FAILED', 'BLOCKED', name='crm_sync_attempt_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crm_record_id'], ['crm_records.id'], name=op.f('fk_crm_sync_attempts_crm_record_id_crm_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_crm_sync_attempts_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_sync_attempts')),
    sa.UniqueConstraint('idempotency_key', name='uq_crm_sync_idempotency_key')
    )
    op.create_index('ix_crm_sync_record_time', 'crm_sync_attempts', ['crm_record_id', 'created_at'], unique=False)
    op.create_table('organization_addresses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('address_type', sa.String(length=60), nullable=True),
    sa.Column('line1', sa.String(length=300), nullable=True),
    sa.Column('line2', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('normalized_address', sa.String(length=900), nullable=True),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_addresses_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_organization_addresses_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_addresses'))
    )
    op.create_index(op.f('ix_organization_addresses_normalized_address'), 'organization_addresses', ['normalized_address'], unique=False)
    op.create_table('organization_aliases',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized_alias', sa.String(length=300), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('alias_type', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_aliases_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_organization_aliases_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_aliases')),
    sa.UniqueConstraint('organization_id', 'normalized_alias', name='uq_org_alias_normalized')
    )
    op.create_index('ix_org_alias_lookup', 'organization_aliases', ['normalized_alias'], unique=False)
    op.create_table('organization_domains',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('normalized_domain', sa.String(length=255), nullable=False),
    sa.Column('relationship_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='organization_domain_verification_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_domains_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_organization_domains_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_domains')),
    sa.UniqueConstraint('organization_id', 'normalized_domain', name='uq_org_domain')
    )
    op.create_index('ix_org_domain_lookup', 'organization_domains', ['normalized_domain'], unique=False)
    op.create_table('person_aliases',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=240), nullable=False),
    sa.Column('normalized_alias', sa.String(length=240), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_aliases_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_person_aliases_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_aliases')),
    sa.UniqueConstraint('person_id', 'normalized_alias', name='uq_person_alias_normalized')
    )
    op.create_index('ix_person_alias_lookup', 'person_aliases', ['normalized_alias'], unique=False)
    op.create_table('person_contact_points',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('contact_type', sa.Enum('EMAIL', 'PHONE', 'FAX', 'URL', 'OTHER', name='contact_point_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=False),
    sa.Column('pii_class', sa.Enum('NONE', 'PUBLIC_BUSINESS', 'BUSINESS_CONTACT', 'PERSONAL_CONTACT', 'SENSITIVE', 'SECRET', name='contact_point_pii_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('demo_masking_policy', sa.Enum('NONE', 'PARTIAL', 'FULL', 'HIDDEN', name='contact_point_masking_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('verification_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='contact_point_verification_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_person_contact_points_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_contact_points_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_person_contact_points_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_contact_points'))
    )
    op.create_index('ix_contact_point_normalized', 'person_contact_points', ['contact_type', 'normalized_value'], unique=False)
    op.create_table('product_fit_assessments',
    sa.Column('opportunity_assessment_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('fit_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('fit_band', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='product_fit_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_state', sa.Enum('UNKNOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CONFLICTED', name='product_fit_confidence_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('missing_evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fit_score >= 0 AND fit_score <= 100', name=op.f('ck_product_fit_assessments_fit_score_range')),
    sa.ForeignKeyConstraint(['opportunity_assessment_id'], ['opportunity_assessments.id'], name=op.f('fk_product_fit_assessments_opportunity_assessment_id_opportunity_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_fit_assessments')),
    sa.UniqueConstraint('opportunity_assessment_id', 'product_code', name='uq_product_fit_assessment')
    )
    op.create_table('project_organizations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('verification_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='project_organization_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_organizations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_organizations_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_project_organizations_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_organizations')),
    sa.UniqueConstraint('project_id', 'organization_id', 'role', name='uq_project_organization_role')
    )
    op.create_table('project_persons',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('association_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='project_person_association_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_persons_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_project_persons_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_persons_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_project_persons_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_persons')),
    sa.UniqueConstraint('project_id', 'person_id', 'role', name='uq_project_person_role')
    )
    op.create_table('project_relationships',
    sa.Column('parent_project_id', sa.Uuid(), nullable=False),
    sa.Column('child_project_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=60), nullable=False),
    sa.Column('verification_state', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='project_relationship_verification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('parent_project_id <> child_project_id', name=op.f('ck_project_relationships_not_self_relationship')),
    sa.ForeignKeyConstraint(['child_project_id'], ['projects.id'], name=op.f('fk_project_relationships_child_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.id'], name=op.f('fk_project_relationships_parent_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_project_relationships_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_relationships')),
    sa.UniqueConstraint('parent_project_id', 'child_project_id', 'relationship_type', name='uq_project_relationship')
    )
    op.create_table('project_signals',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('signal_key', sa.String(length=160), nullable=False),
    sa.Column('signal_value', sa.String(length=400), nullable=True),
    sa.Column('classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='project_signal_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_project_signals_confidence_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_signals_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observations.id'], name=op.f('fk_project_signals_source_observation_id_source_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_signals')),
    sa.UniqueConstraint('project_id', 'signal_key', 'source_observation_id', name='uq_project_signal_source')
    )
    op.create_table('source_evidence',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=240), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'VERIFIED', 'CONFLICTED', 'UNKNOWN', name='source_evidence_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('pii_class', sa.Enum('NONE', 'PUBLIC_BUSINESS', 'BUSINESS_CONTACT', 'PERSONAL_CONTACT', 'SENSITIVE', 'SECRET', name='source_evidence_pii_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('demo_masking_policy', sa.Enum('NONE', 'PARTIAL', 'FULL', 'HIDDEN', name='source_evidence_masking_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_permitted_for_decision', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('page_number IS NULL OR page_number >= 1', name=op.f('ck_source_evidence_page_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_source_evidence_document_id_source_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.id'], name=op.f('fk_source_evidence_observation_id_source_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_evidence')),
    sa.UniqueConstraint('evidence_fingerprint', name='uq_source_evidence_fingerprint')
    )
    op.create_table('ai_claim_evidence',
    sa.Column('ai_claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_claim_id'], ['ai_claims.id'], name=op.f('fk_ai_claim_evidence_ai_claim_id_ai_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], name=op.f('fk_ai_claim_evidence_source_evidence_id_source_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_claim_evidence')),
    sa.UniqueConstraint('ai_claim_id', 'source_evidence_id', name='uq_ai_claim_source_evidence')
    )
    op.create_table('next_actions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('commercial_motion_id', sa.Uuid(), nullable=True),
    sa.Column('dependency_action_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'BLOCKED', 'IN_PROGRESS', 'COMPLETE', 'CANCELLED', name='next_action_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('external_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commercial_motion_id'], ['commercial_motions.id'], name=op.f('fk_next_actions_commercial_motion_id_commercial_motions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_action_id'], ['next_actions.id'], name=op.f('fk_next_actions_dependency_action_id_next_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_evidence_id'], ['external_evidence.id'], name=op.f('fk_next_actions_external_evidence_id_external_evidence'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_next_actions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], name=op.f('fk_next_actions_source_evidence_id_source_evidence'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_actions'))
    )
    op.create_index('ix_next_action_queue', 'next_actions', ['status', 'priority', 'due_at'], unique=False)
    op.create_table('quality_flags',
    sa.Column('rule_code', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='quality_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'WAIVED', name='quality_flag_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('decision_impact', sa.String(length=40), nullable=True),
    sa.Column('blocks_progression', sa.Boolean(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.id'], name=op.f('fk_quality_flags_observation_id_source_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_quality_flags_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_quality_flags_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_quality_flags_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], name=op.f('fk_quality_flags_source_evidence_id_source_evidence'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_flags'))
    )
    op.create_index('ix_quality_flag_open_severity', 'quality_flags', ['state', 'severity'], unique=False)
    op.create_index('ix_quality_flag_subject', 'quality_flags', ['project_id', 'organization_id', 'person_id'], unique=False)
    op.create_table('verification_events',
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('verification_type', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.Enum('UNKNOWN', 'SUPPORTED', 'VERIFIED', 'CONFLICTED', 'REJECTED', name='verification_event_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('external_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=160), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['contact_candidates.id'], name=op.f('fk_verification_events_candidate_id_contact_candidates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_evidence_id'], ['external_evidence.id'], name=op.f('fk_verification_events_external_evidence_id_external_evidence'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_verification_events_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_verification_events_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], name=op.f('fk_verification_events_source_evidence_id_source_evidence'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_events'))
    )
    op.create_index('ix_verification_event_person_time', 'verification_events', ['person_id', 'verified_at'], unique=False)
    op.create_table('workflow_exceptions',
    sa.Column('quality_flag_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='workflow_exception_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('recommended_action', sa.Enum('VERIFY', 'CORRECT', 'IGNORE', 'DEFER', 'RETRY', 'ESCALATE', name='exception_resolution_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_workflow_exceptions_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_exceptions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quality_flag_id'], ['quality_flags.id'], name=op.f('fk_workflow_exceptions_quality_flag_id_quality_flags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_exceptions'))
    )
    op.create_index('ix_workflow_exception_queue', 'workflow_exceptions', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_exception_queue', table_name='workflow_exceptions')
    op.drop_table('workflow_exceptions')
    op.drop_index('ix_verification_event_person_time', table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index('ix_quality_flag_subject', table_name='quality_flags')
    op.drop_index('ix_quality_flag_open_severity', table_name='quality_flags')
    op.drop_table('quality_flags')
    op.drop_index('ix_next_action_queue', table_name='next_actions')
    op.drop_table('next_actions')
    op.drop_table('ai_claim_evidence')
    op.drop_table('source_evidence')
    op.drop_table('project_signals')
    op.drop_table('project_relationships')
    op.drop_table('project_persons')
    op.drop_table('project_organizations')
    op.drop_table('product_fit_assessments')
    op.drop_index('ix_contact_point_normalized', table_name='person_contact_points')
    op.drop_table('person_contact_points')
    op.drop_index('ix_person_alias_lookup', table_name='person_aliases')
    op.drop_table('person_aliases')
    op.drop_index('ix_org_domain_lookup', table_name='organization_domains')
    op.drop_table('organization_domains')
    op.drop_index('ix_org_alias_lookup', table_name='organization_aliases')
    op.drop_table('organization_aliases')
    op.drop_index(op.f('ix_organization_addresses_normalized_address'), table_name='organization_addresses')
    op.drop_table('organization_addresses')
    op.drop_index('ix_crm_sync_record_time', table_name='crm_sync_attempts')
    op.drop_table('crm_sync_attempts')
    op.drop_index('ix_contact_assessment_candidate_time', table_name='contact_assessments')
    op.drop_table('contact_assessments')
    op.drop_index('ix_commercial_outcome_project_time', table_name='commercial_outcomes')
    op.drop_table('commercial_outcomes')
    op.drop_table('assessment_factors')
    op.drop_index('ix_ai_claim_run_status', table_name='ai_claims')
    op.drop_table('ai_claims')
    op.drop_index('ix_source_observation_project', table_name='source_observations')
    op.drop_index('ix_source_observation_person', table_name='source_observations')
    op.drop_index('ix_source_observation_org', table_name='source_observations')
    op.drop_index('ix_source_observation_field', table_name='source_observations')
    op.drop_table('source_observations')
    op.drop_index('ix_opportunity_assessment_project_current', table_name='opportunity_assessments')
    op.drop_table('opportunity_assessments')
    op.drop_index('ix_external_evidence_subject', table_name='external_evidence')
    op.drop_table('external_evidence')
    op.drop_table('crm_records')
    op.drop_index('ix_contact_candidate_project_rank', table_name='contact_candidates')
    op.drop_table('contact_candidates')
    op.drop_table('commercial_motions')
    op.drop_table('ai_usage')
    op.drop_table('scoring_configs')
    op.drop_index('ix_prompt_run_task_time', table_name='prompt_runs')
    op.drop_table('prompt_runs')
    op.drop_index(op.f('ix_projects_normalized_name'), table_name='projects')
    op.drop_index('ix_project_stage', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_pipeline_event_run_time', table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index('ix_person_normalized_name', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_field_history_entity_field', table_name='field_history')
    op.drop_table('field_history')
    op.drop_index('ix_audit_event_object_time', table_name='audit_events')
    op.drop_index('ix_audit_event_actor_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_source_documents_external', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_project_groups_normalized_name'), table_name='project_groups')
    op.drop_table('project_groups')
    op.drop_index('ix_pipeline_run_status_time', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_organization_normalized_name', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('config_versions')
    # ### end Alembic commands ###
